START TRANSACTION;

DROP DATABASE IF EXISTS `TRABLR_DB`;
CREATE DATABASE IF NOT EXISTS `TRABLR_DB`;
USE `TRABLR_DB`;

DROP TABLE IF EXISTS `USER_INFO`;
CREATE TABLE IF NOT EXISTS `USER_INFO` (
    `USER_ID`       INT(11) NOT NULL AUTO_INCREMENT,
    `EMAIL`         VARCHAR(45) NOT NULL,
    `PASSWORD`      VARCHAR(256) NOT NULL,
    `FIRST_NAME`    VARCHAR(45) NOT NULL,
    PRIMARY KEY (`USER_ID`),
    UNIQUE (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 COMMENT='USER_INFO';

DROP TABLE IF EXISTS `TRANSIT_INFO`;
CREATE TABLE IF NOT EXISTS `TRANSIT_INFO` (
    `TRANSIT_ID`        INT(11) NOT NULL AUTO_INCREMENT,
    `STOP_ID`           INT(11) NOT NULL,
    `LINE_ID`           INT(11) NOT NULL,
    `STOP_NAME`         VARCHAR(45) NOT NULL,
    `ROUTE_NAME`        VARCHAR(45) NOT NULL,
    `DIRECTION`         VARCHAR(45) NOT NULL,
    `AGENCY_NAME`       VARCHAR(45) NOT NULL,
    PRIMARY KEY (`TRANSIT_ID`),
    UNIQUE (`STOP_ID`,`DIRECTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 COMMENT='TRANSIT_INFO';

DROP TABLE IF EXISTS `USER_FAVORITES`;
CREATE TABLE IF NOT EXISTS `USER_FAVORITES` (
    `FAVORITES_ID`      INT(11) NOT NULL AUTO_INCREMENT,
    `USER_ID`           INT(11) NOT NULL,
    `TRANSIT_ID_START`  INT(11) NOT NULL,
    `TRANSIT_ID_END`    INT(11) NOT NULL,
    `PRIORITY`          INT(11) NOT NULL,
    `CLICK_COUNT`       INT(11) NOT NULL,
    PRIMARY KEY (`FAVORITES_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES USER_INFO(`USER_ID`),
    FOREIGN KEY (`TRANSIT_ID_START`) REFERENCES TRANSIT_INFO(`TRANSIT_ID`),
    FOREIGN KEY (`TRANSIT_ID_END`) REFERENCES TRANSIT_INFO(`TRANSIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 COMMENT='USER_FAVORITES';

INSERT INTO `USER_INFO` (`USER_ID`,`EMAIL`,`PASSWORD`,`FIRST_NAME`) VALUES
(1,'lorenzo.javier@sjsu.edu','70cbe512b00274e995e4c303de2333457cd810ab0ee3ddfb575b01973d8b929f','Lorenzo');

INSERT INTO `TRANSIT_INFO` (`STOP_ID`,`LINE_ID`,`STOP_NAME`,`ROUTE_NAME`,`DIRECTION`,`AGENCY_NAME`) VALUES
(60824,60,'WINCHESTER & NEAL','WINCHESTER TC - GT AMERICA','SOUTH','VTA'),
(65397,60,'WINCHESTER TRANSIT CENTER','WINCHESTER TC - GT AMERICA','NORTH','VTA'),
(65397,60,'WINCHESTER TRANSIT CENTER','WINCHESTER TC - GT AMERICA','SOUTH','VTA'),
(65462,323,'2ND & PASEO DE SAN ANTONIO','DE ANZA COL - DOWNTOWN SAN JO','WEST','VTA'),
(65741,323,'STEVENS CREEK & SANTANA ROW','DE ANZA COL - DOWNTOWN SAN JO','WEST','VTA'),
(60721,60,'WINCHESTER & NEAL','WINCHESTER TC - GT AMERICA','NORTH','VTA');

INSERT INTO `USER_FAVORITES` (`USER_ID`,`TRANSIT_ID_START`,`TRANSIT_ID_END`,`PRIORITY`) VALUES 
(1,1,2,1),
(1,4,5,2);
